### ISSUE TITLE
Include etag/timestamp/hash for courses

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse#28]

**Comment by encukou** [comment]
From https://github.com/messa/pyladies-courseware/issues/165:

> Currently course structure and lesson contents (list of materials...) are retrieved from course API (i.e. naucse API) only when the backend service is starting. So users don't see any changes to the API data source made after that.
> Would it be possible to add some "build timestamp" value so it could be easily detected that something changed without having to HEAD many files instead?

**Comment by hroncok** [comment]
Random thought:

If this is needed for each run separately, we could use the HEAD commit hash of the fork.

If this is needed as one global hash, we cannot use the HEAD commit hash of the main repo, because the forks might have changed while the main repo have not changed.

**Comment by encukou** [comment]
I think a separate tag for each run/course will be better.
