### ISSUE TITLE
Make sure text in SVGs has the proper font

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse#38]
“Naïve” SVGs don't display correctly if the user doesn't have fonts installed. This is tricky to spot from the author's computer :(
See: https://github.com/pyvec/naucse.python.cz/issues/603

Approaches to consider:
* Convert text paths
* Embed fonts
* Use webfonts

**Comment by encukou** [comment]
If we end up using (and requiring) Inkscape, we should also export the images as optimized Plain SVG.

**Comment by hroncok** [comment]
Requiring Inkscape is tricky for "random" contributors.

**Comment by encukou** [comment]
OTOH, random contributors don't need his step.

**Comment by hroncok** [comment]
If we make it optional, correct.
